// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: audit.sql

package repo

import (
	"context"
)

const createAuditEntry = `-- name: CreateAuditEntry :exec
INSERT INTO audit_log (group_id, actor_user_id, action, before, after)
VALUES ($1::uuid, $2::uuid, $3, $4, $5)
`

type CreateAuditEntryParams struct {
	GroupID     string `json:"group_id"`
	ActorUserID string `json:"actor_user_id"`
	Action      string `json:"action"`
	Before      []byte `json:"before"`
	After       []byte `json:"after"`
}

func (q *Queries) CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) error {
	_, err := q.db.Exec(ctx, createAuditEntry,
		arg.GroupID,
		arg.ActorUserID,
		arg.Action,
		arg.Before,
		arg.After,
	)
	return err
}
