// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: expenses.sql

package repo

import (
	"context"
	"time"

	"expense-splitter/types"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (group_id, paid_by, amount_baisa, category, description, occurred_on)
VALUES ($1::uuid, $2::uuid, $3, $4, $5, $6::date)
RETURNING id, created_at
`

type CreateExpenseParams struct {
	GroupID     string                `json:"group_id"`
	PaidBy      string                `json:"paid_by"`
	AmountBaisa int64                 `json:"amount_baisa"`
	Category    types.ExpenseCategory `json:"category"`
	Description string                `json:"description"`
	OccurredOn  string                `json:"occurred_on"`
}

type CreateExpenseRow struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (CreateExpenseRow, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.GroupID,
		arg.PaidBy,
		arg.AmountBaisa,
		arg.Category,
		arg.Description,
		arg.OccurredOn,
	)
	var i CreateExpenseRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, m.user_id AS paid_by, e.amount_baisa, e.category, e.description,
       e.occurred_on::text AS occurred_on, e.created_at
FROM expenses e
JOIN memberships m ON m.id = e.paid_by
WHERE e.group_id = $1::uuid
  AND e.deleted_at IS NULL
  AND ($2::expense_category IS NULL OR e.category = $2::expense_category)
  AND ($3::uuid IS NULL OR m.user_id = $3::uuid)
  AND ($4::text IS NULL OR e.description ILIKE ('%' || $4::text || '%') ESCAPE '\')
ORDER BY e.occurred_on, e.created_at
`

type ListExpensesParams struct {
	GroupID  string                 `json:"group_id"`
	Category *types.ExpenseCategory `json:"category"`
	PaidBy   *string                `json:"paid_by"`
	Search   *string                `json:"search"`
}

type ListExpensesRow struct {
	ID          string                `json:"id"`
	PaidBy      string                `json:"paid_by"`
	AmountBaisa int64                 `json:"amount_baisa"`
	Category    types.ExpenseCategory `json:"category"`
	Description string                `json:"description"`
	OccurredOn  string                `json:"occurred_on"`
	CreatedAt   time.Time             `json:"created_at"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.GroupID,
		arg.Category,
		arg.PaidBy,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesRow
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.PaidBy,
			&i.AmountBaisa,
			&i.Category,
			&i.Description,
			&i.OccurredOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpenseForUpdate = `-- name: LockExpenseForUpdate :one
SELECT e.amount_baisa, m.user_id
FROM expenses e
JOIN memberships m ON m.id = e.paid_by
WHERE e.id = $1::uuid AND e.group_id = $2::uuid AND e.deleted_at IS NULL
FOR UPDATE OF e
`

type LockExpenseForUpdateParams struct {
	ID      string `json:"id"`
	GroupID string `json:"group_id"`
}

type LockExpenseForUpdateRow struct {
	AmountBaisa int64  `json:"amount_baisa"`
	UserID      string `json:"user_id"`
}

func (q *Queries) LockExpenseForUpdate(ctx context.Context, arg LockExpenseForUpdateParams) (LockExpenseForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockExpenseForUpdate, arg.ID, arg.GroupID)
	var i LockExpenseForUpdateRow
	err := row.Scan(&i.AmountBaisa, &i.UserID)
	return i, err
}

const sumPaidByMember = `-- name: SumPaidByMember :many
SELECT paid_by, SUM(amount_baisa)::bigint AS total
FROM expenses
WHERE group_id = $1::uuid AND deleted_at IS NULL
GROUP BY paid_by
`

type SumPaidByMemberRow struct {
	PaidBy string `json:"paid_by"`
	Total  int64  `json:"total"`
}

func (q *Queries) SumPaidByMember(ctx context.Context, groupID string) ([]SumPaidByMemberRow, error) {
	rows, err := q.db.Query(ctx, sumPaidByMember, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumPaidByMemberRow
	for rows.Next() {
		var i SumPaidByMemberRow
		if err := rows.Scan(&i.PaidBy, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumSpendByCategory = `-- name: SumSpendByCategory :many
SELECT category, SUM(amount_baisa)::bigint AS total
FROM expenses
WHERE group_id = $1::uuid AND deleted_at IS NULL
GROUP BY category
`

type SumSpendByCategoryRow struct {
	Category types.ExpenseCategory `json:"category"`
	Total    int64                 `json:"total"`
}

func (q *Queries) SumSpendByCategory(ctx context.Context, groupID string) ([]SumSpendByCategoryRow, error) {
	rows, err := q.db.Query(ctx, sumSpendByCategory, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumSpendByCategoryRow
	for rows.Next() {
		var i SumSpendByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET amount_baisa = $1, category = $2, description = $3,
    occurred_on = $4::date, updated_at = now()
WHERE id = $5::uuid
RETURNING created_at
`

type UpdateExpenseParams struct {
	AmountBaisa int64                 `json:"amount_baisa"`
	Category    types.ExpenseCategory `json:"category"`
	Description string                `json:"description"`
	OccurredOn  string                `json:"occurred_on"`
	ID          string                `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.AmountBaisa,
		arg.Category,
		arg.Description,
		arg.OccurredOn,
		arg.ID,
	)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}
