// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: groups.sql

package repo

import (
	"context"
	"time"

	"expense-splitter/types"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, start_date, end_date, expected_member_count, created_by)
VALUES ($1, $2, $3, $4, $5::uuid)
RETURNING id, name, start_date, end_date, status, invite_token, expected_member_count, created_by, created_at
`

type CreateGroupParams struct {
	Name                string    `json:"name"`
	StartDate           time.Time `json:"start_date"`
	EndDate             time.Time `json:"end_date"`
	ExpectedMemberCount *int      `json:"expected_member_count"`
	CreatedBy           string    `json:"created_by"`
}

type CreateGroupRow struct {
	ID                  string            `json:"id"`
	Name                string            `json:"name"`
	StartDate           time.Time         `json:"start_date"`
	EndDate             time.Time         `json:"end_date"`
	Status              types.GroupStatus `json:"status"`
	InviteToken         string            `json:"invite_token"`
	ExpectedMemberCount *int              `json:"expected_member_count"`
	CreatedBy           string            `json:"created_by"`
	CreatedAt           time.Time         `json:"created_at"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.ExpectedMemberCount,
		arg.CreatedBy,
	)
	var i CreateGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.InviteToken,
		&i.ExpectedMemberCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec
DELETE FROM groups WHERE id = $1::uuid
`

func (q *Queries) DeleteGroup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteGroup, id)
	return err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, start_date, end_date, status, invite_token, status_token, expected_member_count, created_by, created_at
FROM groups
WHERE id = $1::uuid
`

type GetGroupByIDRow struct {
	ID                  string            `json:"id"`
	Name                string            `json:"name"`
	StartDate           time.Time         `json:"start_date"`
	EndDate             time.Time         `json:"end_date"`
	Status              types.GroupStatus `json:"status"`
	InviteToken         string            `json:"invite_token"`
	StatusToken         string            `json:"status_token"`
	ExpectedMemberCount *int              `json:"expected_member_count"`
	CreatedBy           string            `json:"created_by"`
	CreatedAt           time.Time         `json:"created_at"`
}

func (q *Queries) GetGroupByID(ctx context.Context, id string) (GetGroupByIDRow, error) {
	row := q.db.QueryRow(ctx, getGroupByID, id)
	var i GetGroupByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.InviteToken,
		&i.StatusToken,
		&i.ExpectedMemberCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupByInviteToken = `-- name: GetGroupByInviteToken :one
SELECT id, status FROM groups WHERE invite_token = $1::uuid
`

type GetGroupByInviteTokenRow struct {
	ID     string            `json:"id"`
	Status types.GroupStatus `json:"status"`
}

func (q *Queries) GetGroupByInviteToken(ctx context.Context, inviteToken string) (GetGroupByInviteTokenRow, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteToken, inviteToken)
	var i GetGroupByInviteTokenRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getGroupPublicStatus = `-- name: GetGroupPublicStatus :one
SELECT g.name,
       g.status,
       COALESCE((SELECT SUM(e.amount_baisa) FROM expenses e WHERE e.group_id = g.id AND e.deleted_at IS NULL), 0)::bigint AS total_spent,
       COALESCE((SELECT COUNT(*) FROM memberships m WHERE m.group_id = g.id AND m.status = 'approved'), 0)::bigint AS member_count
FROM groups g
WHERE g.status_token = $1::uuid
`

type GetGroupPublicStatusRow struct {
	Name        string            `json:"name"`
	Status      types.GroupStatus `json:"status"`
	TotalSpent  int64             `json:"total_spent"`
	MemberCount int64             `json:"member_count"`
}

func (q *Queries) GetGroupPublicStatus(ctx context.Context, statusToken string) (GetGroupPublicStatusRow, error) {
	row := q.db.QueryRow(ctx, getGroupPublicStatus, statusToken)
	var i GetGroupPublicStatusRow
	err := row.Scan(
		&i.Name,
		&i.Status,
		&i.TotalSpent,
		&i.MemberCount,
	)
	return i, err
}

const getGroupStatus = `-- name: GetGroupStatus :one
SELECT status FROM groups WHERE id = $1::uuid
`

func (q *Queries) GetGroupStatus(ctx context.Context, id string) (types.GroupStatus, error) {
	row := q.db.QueryRow(ctx, getGroupStatus, id)
	var status types.GroupStatus
	err := row.Scan(&status)
	return status, err
}

const groupHasHistory = `-- name: GroupHasHistory :one
SELECT (EXISTS(SELECT 1 FROM expenses WHERE group_id = $1::uuid)
     OR EXISTS(SELECT 1 FROM payments WHERE group_id = $1::uuid)
     OR EXISTS(SELECT 1 FROM settlement_runs WHERE group_id = $1::uuid)
     OR EXISTS(SELECT 1 FROM audit_log WHERE group_id = $1::uuid))::bool AS has_history
`

func (q *Queries) GroupHasHistory(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, groupHasHistory, id)
	var has_history bool
	err := row.Scan(&has_history)
	return has_history, err
}

const listAllGroups = `-- name: ListAllGroups :many
SELECT g.id, g.name, g.start_date, g.end_date, g.status, g.created_by, g.created_at,
       COALESCE((SELECT COUNT(*) FROM memberships m WHERE m.group_id = g.id AND m.status = 'approved'), 0)::bigint AS member_count,
       COALESCE((SELECT SUM(e.amount_baisa) FROM expenses e WHERE e.group_id = g.id AND e.deleted_at IS NULL), 0)::bigint AS total_spent,
       COUNT(*) OVER()::bigint AS full_count
FROM groups g
ORDER BY g.created_at DESC
LIMIT $2::int OFFSET $1::int
`

type ListAllGroupsParams struct {
	PageOffset int32 `json:"page_offset"`
	PageLimit  int32 `json:"page_limit"`
}

type ListAllGroupsRow struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	StartDate   time.Time         `json:"start_date"`
	EndDate     time.Time         `json:"end_date"`
	Status      types.GroupStatus `json:"status"`
	CreatedBy   string            `json:"created_by"`
	CreatedAt   time.Time         `json:"created_at"`
	MemberCount int64             `json:"member_count"`
	TotalSpent  int64             `json:"total_spent"`
	FullCount   int64             `json:"full_count"`
}

func (q *Queries) ListAllGroups(ctx context.Context, arg ListAllGroupsParams) ([]ListAllGroupsRow, error) {
	rows, err := q.db.Query(ctx, listAllGroups, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGroupsRow
	for rows.Next() {
		var i ListAllGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.MemberCount,
			&i.TotalSpent,
			&i.FullCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsForUser = `-- name: ListGroupsForUser :many
SELECT g.id, g.name, g.start_date, g.end_date, g.status, g.invite_token,
       g.expected_member_count, g.created_by, g.created_at,
       m.role, m.status AS membership_status
FROM groups g
JOIN memberships m ON m.group_id = g.id
WHERE m.user_id = $1::uuid AND m.status = 'approved'
ORDER BY g.created_at DESC
`

type ListGroupsForUserRow struct {
	ID                  string                 `json:"id"`
	Name                string                 `json:"name"`
	StartDate           time.Time              `json:"start_date"`
	EndDate             time.Time              `json:"end_date"`
	Status              types.GroupStatus      `json:"status"`
	InviteToken         string                 `json:"invite_token"`
	ExpectedMemberCount *int                   `json:"expected_member_count"`
	CreatedBy           string                 `json:"created_by"`
	CreatedAt           time.Time              `json:"created_at"`
	Role                types.MembershipRole   `json:"role"`
	MembershipStatus    types.MembershipStatus `json:"membership_status"`
}

func (q *Queries) ListGroupsForUser(ctx context.Context, userID string) ([]ListGroupsForUserRow, error) {
	rows, err := q.db.Query(ctx, listGroupsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsForUserRow
	for rows.Next() {
		var i ListGroupsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StartDate,
			&i.EndDate,
			&i.Status,
			&i.InviteToken,
			&i.ExpectedMemberCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Role,
			&i.MembershipStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockGroup = `-- name: LockGroup :one
SELECT status FROM groups WHERE id = $1::uuid FOR UPDATE
`

func (q *Queries) LockGroup(ctx context.Context, id string) (types.GroupStatus, error) {
	row := q.db.QueryRow(ctx, lockGroup, id)
	var status types.GroupStatus
	err := row.Scan(&status)
	return status, err
}

const lockGroupForExpense = `-- name: LockGroupForExpense :one
SELECT status, ($1::date BETWEEN start_date::date AND end_date::date)::bool AS in_range
FROM groups
WHERE id = $2::uuid
FOR SHARE
`

type LockGroupForExpenseParams struct {
	OccurredOn string `json:"occurred_on"`
	ID         string `json:"id"`
}

type LockGroupForExpenseRow struct {
	Status  types.GroupStatus `json:"status"`
	InRange bool              `json:"in_range"`
}

func (q *Queries) LockGroupForExpense(ctx context.Context, arg LockGroupForExpenseParams) (LockGroupForExpenseRow, error) {
	row := q.db.QueryRow(ctx, lockGroupForExpense, arg.OccurredOn, arg.ID)
	var i LockGroupForExpenseRow
	err := row.Scan(&i.Status, &i.InRange)
	return i, err
}

const lockGroupStatus = `-- name: LockGroupStatus :one
SELECT status FROM groups WHERE id = $1::uuid FOR SHARE
`

func (q *Queries) LockGroupStatus(ctx context.Context, id string) (types.GroupStatus, error) {
	row := q.db.QueryRow(ctx, lockGroupStatus, id)
	var status types.GroupStatus
	err := row.Scan(&status)
	return status, err
}

const markGroupClosed = `-- name: MarkGroupClosed :exec
UPDATE groups SET status = 'closed', updated_at = now() WHERE id = $1::uuid
`

func (q *Queries) MarkGroupClosed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markGroupClosed, id)
	return err
}

const markGroupSettled = `-- name: MarkGroupSettled :exec
UPDATE groups SET status = 'settled', updated_at = now()
WHERE id = $1::uuid AND status = 'closed'
`

func (q *Queries) MarkGroupSettled(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markGroupSettled, id)
	return err
}

const updateOpenGroup = `-- name: UpdateOpenGroup :one
UPDATE groups
SET name = $1, start_date = $2, end_date = $3,
    expected_member_count = $4, updated_at = now()
WHERE id = $5::uuid AND status = 'open'
RETURNING id, name, start_date, end_date, status, invite_token, expected_member_count, created_by, created_at
`

type UpdateOpenGroupParams struct {
	Name                string    `json:"name"`
	StartDate           time.Time `json:"start_date"`
	EndDate             time.Time `json:"end_date"`
	ExpectedMemberCount *int      `json:"expected_member_count"`
	ID                  string    `json:"id"`
}

type UpdateOpenGroupRow struct {
	ID                  string            `json:"id"`
	Name                string            `json:"name"`
	StartDate           time.Time         `json:"start_date"`
	EndDate             time.Time         `json:"end_date"`
	Status              types.GroupStatus `json:"status"`
	InviteToken         string            `json:"invite_token"`
	ExpectedMemberCount *int              `json:"expected_member_count"`
	CreatedBy           string            `json:"created_by"`
	CreatedAt           time.Time         `json:"created_at"`
}

func (q *Queries) UpdateOpenGroup(ctx context.Context, arg UpdateOpenGroupParams) (UpdateOpenGroupRow, error) {
	row := q.db.QueryRow(ctx, updateOpenGroup,
		arg.Name,
		arg.StartDate,
		arg.EndDate,
		arg.ExpectedMemberCount,
		arg.ID,
	)
	var i UpdateOpenGroupRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StartDate,
		&i.EndDate,
		&i.Status,
		&i.InviteToken,
		&i.ExpectedMemberCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
