// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: memberships.sql

package repo

import (
	"context"
	"time"

	"expense-splitter/types"
)

const createGroupAdminMembership = `-- name: CreateGroupAdminMembership :exec
INSERT INTO memberships (group_id, user_id, role, status)
VALUES ($1::uuid, $2::uuid, 'group_admin', 'approved')
`

type CreateGroupAdminMembershipParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

func (q *Queries) CreateGroupAdminMembership(ctx context.Context, arg CreateGroupAdminMembershipParams) error {
	_, err := q.db.Exec(ctx, createGroupAdminMembership, arg.GroupID, arg.UserID)
	return err
}

const createJoinRequest = `-- name: CreateJoinRequest :one
INSERT INTO memberships (group_id, user_id)
VALUES ($1::uuid, $2::uuid)
ON CONFLICT (group_id, user_id) DO NOTHING
RETURNING role, status, created_at
`

type CreateJoinRequestParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

type CreateJoinRequestRow struct {
	Role      types.MembershipRole   `json:"role"`
	Status    types.MembershipStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (CreateJoinRequestRow, error) {
	row := q.db.QueryRow(ctx, createJoinRequest, arg.GroupID, arg.UserID)
	var i CreateJoinRequestRow
	err := row.Scan(&i.Role, &i.Status, &i.CreatedAt)
	return i, err
}

const decideJoinRequest = `-- name: DecideJoinRequest :one
UPDATE memberships
SET status = $1, updated_at = now()
WHERE group_id = $2::uuid AND user_id = $3::uuid AND status = 'requested'
RETURNING role, status, created_at
`

type DecideJoinRequestParams struct {
	Status  types.MembershipStatus `json:"status"`
	GroupID string                 `json:"group_id"`
	UserID  string                 `json:"user_id"`
}

type DecideJoinRequestRow struct {
	Role      types.MembershipRole   `json:"role"`
	Status    types.MembershipStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
}

func (q *Queries) DecideJoinRequest(ctx context.Context, arg DecideJoinRequestParams) (DecideJoinRequestRow, error) {
	row := q.db.QueryRow(ctx, decideJoinRequest, arg.Status, arg.GroupID, arg.UserID)
	var i DecideJoinRequestRow
	err := row.Scan(&i.Role, &i.Status, &i.CreatedAt)
	return i, err
}

const deleteMembership = `-- name: DeleteMembership :exec
DELETE FROM memberships WHERE id = $1::uuid
`

func (q *Queries) DeleteMembership(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMembership, id)
	return err
}

const demoteGroupAdmin = `-- name: DemoteGroupAdmin :exec
UPDATE memberships
SET role = 'member', updated_at = now()
WHERE group_id = $1::uuid AND role = 'group_admin'
`

func (q *Queries) DemoteGroupAdmin(ctx context.Context, groupID string) error {
	_, err := q.db.Exec(ctx, demoteGroupAdmin, groupID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT id, role, status
FROM memberships
WHERE group_id = $1::uuid AND user_id = $2::uuid
`

type GetMembershipParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

type GetMembershipRow struct {
	ID     string                 `json:"id"`
	Role   types.MembershipRole   `json:"role"`
	Status types.MembershipStatus `json:"status"`
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.GroupID, arg.UserID)
	var i GetMembershipRow
	err := row.Scan(&i.ID, &i.Role, &i.Status)
	return i, err
}

const listApprovedMembers = `-- name: ListApprovedMembers :many
SELECT id, user_id
FROM memberships
WHERE group_id = $1::uuid AND status = 'approved'
ORDER BY user_id
`

type ListApprovedMembersRow struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListApprovedMembers(ctx context.Context, groupID string) ([]ListApprovedMembersRow, error) {
	rows, err := q.db.Query(ctx, listApprovedMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedMembersRow
	for rows.Next() {
		var i ListApprovedMembersRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT m.user_id, u.email, m.role, m.status, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1::uuid
ORDER BY m.role, m.created_at
`

type ListGroupMembersRow struct {
	UserID    string                 `json:"user_id"`
	Email     string                 `json:"email"`
	Role      types.MembershipRole   `json:"role"`
	Status    types.MembershipStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID string) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJoinRequests = `-- name: ListJoinRequests :many
SELECT m.user_id, u.email, m.role, m.status, m.created_at
FROM memberships m
JOIN users u ON u.id = m.user_id
WHERE m.group_id = $1::uuid AND m.status = 'requested'
ORDER BY m.created_at
`

type ListJoinRequestsRow struct {
	UserID    string                 `json:"user_id"`
	Email     string                 `json:"email"`
	Role      types.MembershipRole   `json:"role"`
	Status    types.MembershipStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
}

func (q *Queries) ListJoinRequests(ctx context.Context, groupID string) ([]ListJoinRequestsRow, error) {
	rows, err := q.db.Query(ctx, listJoinRequests, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJoinRequestsRow
	for rows.Next() {
		var i ListJoinRequestsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const membershipHasExpenses = `-- name: MembershipHasExpenses :one
SELECT EXISTS(
  SELECT 1 FROM expenses WHERE group_id = $1::uuid AND paid_by = $2::uuid
) AS has_expenses
`

type MembershipHasExpensesParams struct {
	GroupID string `json:"group_id"`
	PaidBy  string `json:"paid_by"`
}

func (q *Queries) MembershipHasExpenses(ctx context.Context, arg MembershipHasExpensesParams) (bool, error) {
	row := q.db.QueryRow(ctx, membershipHasExpenses, arg.GroupID, arg.PaidBy)
	var has_expenses bool
	err := row.Scan(&has_expenses)
	return has_expenses, err
}

const promoteToGroupAdmin = `-- name: PromoteToGroupAdmin :one
UPDATE memberships
SET role = 'group_admin', updated_at = now()
WHERE group_id = $1::uuid AND user_id = $2::uuid AND status = 'approved'
RETURNING role, status, created_at
`

type PromoteToGroupAdminParams struct {
	GroupID string `json:"group_id"`
	UserID  string `json:"user_id"`
}

type PromoteToGroupAdminRow struct {
	Role      types.MembershipRole   `json:"role"`
	Status    types.MembershipStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
}

func (q *Queries) PromoteToGroupAdmin(ctx context.Context, arg PromoteToGroupAdminParams) (PromoteToGroupAdminRow, error) {
	row := q.db.QueryRow(ctx, promoteToGroupAdmin, arg.GroupID, arg.UserID)
	var i PromoteToGroupAdminRow
	err := row.Scan(&i.Role, &i.Status, &i.CreatedAt)
	return i, err
}
