// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"database/sql/driver"
	"fmt"
	"time"

	"expense-splitter/types"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExpenseCategory string

const (
	ExpenseCategoryLodging   ExpenseCategory = "lodging"
	ExpenseCategoryFuel      ExpenseCategory = "fuel"
	ExpenseCategoryFood      ExpenseCategory = "food"
	ExpenseCategoryTransport ExpenseCategory = "transport"
	ExpenseCategoryOther     ExpenseCategory = "other"
)

func (e *ExpenseCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseCategory(s)
	case string:
		*e = ExpenseCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseCategory: %T", src)
	}
	return nil
}

type NullExpenseCategory struct {
	ExpenseCategory ExpenseCategory `json:"expense_category"`
	Valid           bool            `json:"valid"` // Valid is true if ExpenseCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseCategory) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseCategory), nil
}

type GroupStatus string

const (
	GroupStatusOpen    GroupStatus = "open"
	GroupStatusClosed  GroupStatus = "closed"
	GroupStatusSettled GroupStatus = "settled"
)

func (e *GroupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GroupStatus(s)
	case string:
		*e = GroupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for GroupStatus: %T", src)
	}
	return nil
}

type NullGroupStatus struct {
	GroupStatus GroupStatus `json:"group_status"`
	Valid       bool        `json:"valid"` // Valid is true if GroupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGroupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.GroupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GroupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGroupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GroupStatus), nil
}

type MembershipRole string

const (
	MembershipRoleGroupAdmin MembershipRole = "group_admin"
	MembershipRoleMember     MembershipRole = "member"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

type MembershipStatus string

const (
	MembershipStatusRequested MembershipStatus = "requested"
	MembershipStatusApproved  MembershipStatus = "approved"
	MembershipStatusRejected  MembershipStatus = "rejected"
)

func (e *MembershipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipStatus(s)
	case string:
		*e = MembershipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipStatus: %T", src)
	}
	return nil
}

type NullMembershipStatus struct {
	MembershipStatus MembershipStatus `json:"membership_status"`
	Valid            bool             `json:"valid"` // Valid is true if MembershipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipStatus), nil
}

type NudgeType string

const (
	NudgeTypeDebtor   NudgeType = "debtor"
	NudgeTypeCreditor NudgeType = "creditor"
)

func (e *NudgeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NudgeType(s)
	case string:
		*e = NudgeType(s)
	default:
		return fmt.Errorf("unsupported scan type for NudgeType: %T", src)
	}
	return nil
}

type NullNudgeType struct {
	NudgeType NudgeType `json:"nudge_type"`
	Valid     bool      `json:"valid"` // Valid is true if NudgeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNudgeType) Scan(value interface{}) error {
	if value == nil {
		ns.NudgeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NudgeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNudgeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NudgeType), nil
}

type PaymentStatus string

const (
	PaymentStatusPending           PaymentStatus = "pending"
	PaymentStatusProofSubmitted    PaymentStatus = "proof_submitted"
	PaymentStatusCreditorConfirmed PaymentStatus = "creditor_confirmed"
	PaymentStatusDisputed          PaymentStatus = "disputed"
	PaymentStatusSettled           PaymentStatus = "settled"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type ProofType string

const (
	ProofTypeImage ProofType = "image"
	ProofTypeText  ProofType = "text"
)

func (e *ProofType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProofType(s)
	case string:
		*e = ProofType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProofType: %T", src)
	}
	return nil
}

type NullProofType struct {
	ProofType ProofType `json:"proof_type"`
	Valid     bool      `json:"valid"` // Valid is true if ProofType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProofType) Scan(value interface{}) error {
	if value == nil {
		ns.ProofType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProofType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProofType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProofType), nil
}

type SplitType string

const (
	SplitTypeEqual    SplitType = "equal"
	SplitTypeSubset   SplitType = "subset"
	SplitTypeWeighted SplitType = "weighted"
)

func (e *SplitType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SplitType(s)
	case string:
		*e = SplitType(s)
	default:
		return fmt.Errorf("unsupported scan type for SplitType: %T", src)
	}
	return nil
}

type NullSplitType struct {
	SplitType SplitType `json:"split_type"`
	Valid     bool      `json:"valid"` // Valid is true if SplitType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSplitType) Scan(value interface{}) error {
	if value == nil {
		ns.SplitType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SplitType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSplitType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SplitType), nil
}

type VerificationStatus string

const (
	VerificationStatusRegistered          VerificationStatus = "registered"
	VerificationStatusPendingVerification VerificationStatus = "pending_verification"
	VerificationStatusVerified            VerificationStatus = "verified"
	VerificationStatusRejected            VerificationStatus = "rejected"
)

func (e *VerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationStatus(s)
	case string:
		*e = VerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationStatus: %T", src)
	}
	return nil
}

type NullVerificationStatus struct {
	VerificationStatus VerificationStatus `json:"verification_status"`
	Valid              bool               `json:"valid"` // Valid is true if VerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationStatus), nil
}

type AuditLog struct {
	ID          int64     `json:"id"`
	GroupID     *string   `json:"group_id"`
	ActorUserID *string   `json:"actor_user_id"`
	Action      string    `json:"action"`
	Before      []byte    `json:"before"`
	After       []byte    `json:"after"`
	CreatedAt   time.Time `json:"created_at"`
}

type Expense struct {
	ID          string                `json:"id"`
	GroupID     string                `json:"group_id"`
	PaidBy      string                `json:"paid_by"`
	AmountBaisa int64                 `json:"amount_baisa"`
	Category    types.ExpenseCategory `json:"category"`
	Description string                `json:"description"`
	OccurredOn  string                `json:"occurred_on"`
	SplitType   types.SplitType       `json:"split_type"`
	DeletedAt   pgtype.Timestamptz    `json:"deleted_at"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type ExpenseShare struct {
	ID        string `json:"id"`
	ExpenseID string `json:"expense_id"`
	UserID    string `json:"user_id"`
	Weight    int32  `json:"weight"`
}

type Group struct {
	ID                  string            `json:"id"`
	Name                string            `json:"name"`
	StartDate           time.Time         `json:"start_date"`
	EndDate             time.Time         `json:"end_date"`
	Status              types.GroupStatus `json:"status"`
	InviteToken         string            `json:"invite_token"`
	StatusToken         string            `json:"status_token"`
	ExpectedMemberCount *int              `json:"expected_member_count"`
	CreatedBy           string            `json:"created_by"`
	CreatedAt           time.Time         `json:"created_at"`
	UpdatedAt           time.Time         `json:"updated_at"`
}

type Membership struct {
	ID        string                 `json:"id"`
	GroupID   string                 `json:"group_id"`
	UserID    string                 `json:"user_id"`
	Role      types.MembershipRole   `json:"role"`
	Status    types.MembershipStatus `json:"status"`
	CreatedAt time.Time              `json:"created_at"`
	UpdatedAt time.Time              `json:"updated_at"`
}

type Notification struct {
	ID              string          `json:"id"`
	PaymentID       string          `json:"payment_id"`
	RecipientUserID string          `json:"recipient_user_id"`
	NudgeType       types.NudgeType `json:"nudge_type"`
	LastSentAt      time.Time       `json:"last_sent_at"`
}

type Payment struct {
	ID              string              `json:"id"`
	SettlementRunID string              `json:"settlement_run_id"`
	GroupID         string              `json:"group_id"`
	FromUserID      string              `json:"from_user_id"`
	ToUserID        string              `json:"to_user_id"`
	AmountBaisa     int64               `json:"amount_baisa"`
	Status          types.PaymentStatus `json:"status"`
	Version         int32               `json:"version"`
	CreatedAt       time.Time           `json:"created_at"`
	UpdatedAt       time.Time           `json:"updated_at"`
}

type Proof struct {
	ID        string          `json:"id"`
	PaymentID string          `json:"payment_id"`
	ProofType types.ProofType `json:"proof_type"`
	Sha256    *string         `json:"sha256"`
	ByteSize  *int64          `json:"byte_size"`
	IsCurrent bool            `json:"is_current"`
	CreatedAt time.Time       `json:"created_at"`
	Note      *string         `json:"note"`
}

type SettlementRun struct {
	ID         string    `json:"id"`
	GroupID    string    `json:"group_id"`
	ComputedBy string    `json:"computed_by"`
	Snapshot   []byte    `json:"snapshot"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
	VerifiedBy         *string                  `json:"verified_by"`
	CreatedAt          time.Time                `json:"created_at"`
	UpdatedAt          time.Time                `json:"updated_at"`
	KeycloakID         *string                  `json:"keycloak_id"`
}
