// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: nudges.sql

package repo

import (
	"context"

	"expense-splitter/types"
)

const listStalePayments = `-- name: ListStalePayments :many
SELECT id, from_user_id, to_user_id, amount_baisa, status
FROM payments
WHERE group_id = $1::uuid
  AND status IN ('pending', 'proof_submitted')
  AND updated_at < now() - make_interval(hours => $2::int)
ORDER BY created_at, id
`

type ListStalePaymentsParams struct {
	GroupID string `json:"group_id"`
	Hours   int32  `json:"hours"`
}

type ListStalePaymentsRow struct {
	ID          string              `json:"id"`
	FromUserID  string              `json:"from_user_id"`
	ToUserID    string              `json:"to_user_id"`
	AmountBaisa int64               `json:"amount_baisa"`
	Status      types.PaymentStatus `json:"status"`
}

func (q *Queries) ListStalePayments(ctx context.Context, arg ListStalePaymentsParams) ([]ListStalePaymentsRow, error) {
	rows, err := q.db.Query(ctx, listStalePayments, arg.GroupID, arg.Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStalePaymentsRow
	for rows.Next() {
		var i ListStalePaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.AmountBaisa,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNudge = `-- name: UpsertNudge :one
INSERT INTO notifications (payment_id, recipient_user_id, nudge_type)
VALUES ($1::uuid, $2::uuid, $3)
ON CONFLICT (payment_id, recipient_user_id, nudge_type)
DO UPDATE SET last_sent_at = now()
WHERE notifications.last_sent_at < now() - make_interval(hours => $4::int)
RETURNING id
`

type UpsertNudgeParams struct {
	PaymentID       string          `json:"payment_id"`
	RecipientUserID string          `json:"recipient_user_id"`
	NudgeType       types.NudgeType `json:"nudge_type"`
	Hours           int32           `json:"hours"`
}

func (q *Queries) UpsertNudge(ctx context.Context, arg UpsertNudgeParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertNudge,
		arg.PaymentID,
		arg.RecipientUserID,
		arg.NudgeType,
		arg.Hours,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
