// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payments.sql

package repo

import (
	"context"
	"time"

	"expense-splitter/types"
)

const listPayments = `-- name: ListPayments :many
SELECT id, from_user_id, to_user_id, amount_baisa, status, created_at
FROM payments
WHERE group_id = $1::uuid
ORDER BY created_at, id
`

type ListPaymentsRow struct {
	ID          string              `json:"id"`
	FromUserID  string              `json:"from_user_id"`
	ToUserID    string              `json:"to_user_id"`
	AmountBaisa int64               `json:"amount_baisa"`
	Status      types.PaymentStatus `json:"status"`
	CreatedAt   time.Time           `json:"created_at"`
}

func (q *Queries) ListPayments(ctx context.Context, groupID string) ([]ListPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPayments, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymentsRow
	for rows.Next() {
		var i ListPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FromUserID,
			&i.ToUserID,
			&i.AmountBaisa,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
