// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: settlement.sql

package repo

import (
	"context"
)

const createPayment = `-- name: CreatePayment :exec
INSERT INTO payments (settlement_run_id, group_id, from_user_id, to_user_id, amount_baisa)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5)
`

type CreatePaymentParams struct {
	SettlementRunID string `json:"settlement_run_id"`
	GroupID         string `json:"group_id"`
	FromUserID      string `json:"from_user_id"`
	ToUserID        string `json:"to_user_id"`
	AmountBaisa     int64  `json:"amount_baisa"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) error {
	_, err := q.db.Exec(ctx, createPayment,
		arg.SettlementRunID,
		arg.GroupID,
		arg.FromUserID,
		arg.ToUserID,
		arg.AmountBaisa,
	)
	return err
}

const createSettlementRun = `-- name: CreateSettlementRun :one
INSERT INTO settlement_runs (group_id, computed_by, snapshot)
VALUES ($1::uuid, $2::uuid, $3)
RETURNING id
`

type CreateSettlementRunParams struct {
	GroupID    string `json:"group_id"`
	ComputedBy string `json:"computed_by"`
	Snapshot   []byte `json:"snapshot"`
}

func (q *Queries) CreateSettlementRun(ctx context.Context, arg CreateSettlementRunParams) (string, error) {
	row := q.db.QueryRow(ctx, createSettlementRun, arg.GroupID, arg.ComputedBy, arg.Snapshot)
	var id string
	err := row.Scan(&id)
	return id, err
}
