// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package repo

import (
	"context"
	"time"

	"expense-splitter/types"
)

const countUserMemberships = `-- name: CountUserMemberships :one
SELECT COUNT(*)::bigint FROM memberships WHERE user_id = $1::uuid
`

func (q *Queries) CountUserMemberships(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserMemberships, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (keycloak_id, email)
VALUES ($1::uuid, $2)
ON CONFLICT (email) DO NOTHING
RETURNING id, email, is_global_admin, verification_status
`

type CreateUserParams struct {
	KeycloakID string `json:"keycloak_id"`
	Email      string `json:"email"`
}

type CreateUserRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.KeycloakID, arg.Email)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.VerificationStatus,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1::uuid
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserAdminView = `-- name: GetUserAdminView :one
SELECT id, email, is_global_admin, verification_status, (keycloak_id IS NOT NULL)::bool AS linked, created_at
FROM users
WHERE id = $1::uuid
`

type GetUserAdminViewRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
	Linked             bool                     `json:"linked"`
	CreatedAt          time.Time                `json:"created_at"`
}

func (q *Queries) GetUserAdminView(ctx context.Context, id string) (GetUserAdminViewRow, error) {
	row := q.db.QueryRow(ctx, getUserAdminView, id)
	var i GetUserAdminViewRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.VerificationStatus,
		&i.Linked,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, is_global_admin, verification_status
FROM users
WHERE id = $1::uuid
`

type GetUserByIDRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.VerificationStatus,
	)
	return i, err
}

const getUserByKeycloakID = `-- name: GetUserByKeycloakID :one
SELECT id, email, is_global_admin, verification_status
FROM users
WHERE keycloak_id = $1::uuid
`

type GetUserByKeycloakIDRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
}

func (q *Queries) GetUserByKeycloakID(ctx context.Context, keycloakID string) (GetUserByKeycloakIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByKeycloakID, keycloakID)
	var i GetUserByKeycloakIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.VerificationStatus,
	)
	return i, err
}

const linkUserKeycloakID = `-- name: LinkUserKeycloakID :one
UPDATE users
SET keycloak_id = $1::uuid, updated_at = now()
WHERE email = $2 AND keycloak_id IS NULL
RETURNING id, email, is_global_admin, verification_status
`

type LinkUserKeycloakIDParams struct {
	KeycloakID string `json:"keycloak_id"`
	Email      string `json:"email"`
}

type LinkUserKeycloakIDRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
}

func (q *Queries) LinkUserKeycloakID(ctx context.Context, arg LinkUserKeycloakIDParams) (LinkUserKeycloakIDRow, error) {
	row := q.db.QueryRow(ctx, linkUserKeycloakID, arg.KeycloakID, arg.Email)
	var i LinkUserKeycloakIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.VerificationStatus,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, is_global_admin, verification_status, (keycloak_id IS NOT NULL)::bool AS linked, created_at,
       COUNT(*) OVER()::bigint AS full_count
FROM users
WHERE ($1::verification_status IS NULL OR verification_status = $1::verification_status)
ORDER BY created_at
LIMIT $3::int OFFSET $2::int
`

type ListUsersParams struct {
	Status     *types.VerificationStatus `json:"status"`
	PageOffset int32                     `json:"page_offset"`
	PageLimit  int32                     `json:"page_limit"`
}

type ListUsersRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
	Linked             bool                     `json:"linked"`
	CreatedAt          time.Time                `json:"created_at"`
	FullCount          int64                    `json:"full_count"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.IsGlobalAdmin,
			&i.VerificationStatus,
			&i.Linked,
			&i.CreatedAt,
			&i.FullCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedGlobalAdmin = `-- name: SeedGlobalAdmin :execrows
INSERT INTO users (email, is_global_admin, verification_status)
VALUES ($1, true, 'verified')
ON CONFLICT (email) DO UPDATE
	SET is_global_admin = true, verification_status = 'verified'
	WHERE users.is_global_admin = false OR users.verification_status <> 'verified'
`

func (q *Queries) SeedGlobalAdmin(ctx context.Context, email string) (int64, error) {
	result, err := q.db.Exec(ctx, seedGlobalAdmin, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserVerification = `-- name: SetUserVerification :one
UPDATE users
SET verification_status = $1, verified_by = $2::uuid, updated_at = now()
WHERE id = $3::uuid
RETURNING id, email, is_global_admin, verification_status
`

type SetUserVerificationParams struct {
	Status     types.VerificationStatus `json:"status"`
	VerifiedBy string                   `json:"verified_by"`
	ID         string                   `json:"id"`
}

type SetUserVerificationRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
}

func (q *Queries) SetUserVerification(ctx context.Context, arg SetUserVerificationParams) (SetUserVerificationRow, error) {
	row := q.db.QueryRow(ctx, setUserVerification, arg.Status, arg.VerifiedBy, arg.ID)
	var i SetUserVerificationRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.VerificationStatus,
	)
	return i, err
}

const setUserVerificationPending = `-- name: SetUserVerificationPending :one
UPDATE users
SET verification_status = 'pending_verification', updated_at = now()
WHERE id = $1::uuid
RETURNING id, email, is_global_admin, verification_status
`

type SetUserVerificationPendingRow struct {
	ID                 string                   `json:"id"`
	Email              string                   `json:"email"`
	IsGlobalAdmin      bool                     `json:"is_global_admin"`
	VerificationStatus types.VerificationStatus `json:"verification_status"`
}

func (q *Queries) SetUserVerificationPending(ctx context.Context, id string) (SetUserVerificationPendingRow, error) {
	row := q.db.QueryRow(ctx, setUserVerificationPending, id)
	var i SetUserVerificationPendingRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsGlobalAdmin,
		&i.VerificationStatus,
	)
	return i, err
}
